### ISSUE TITLE
Callout with :icons: font not styled as ball

### ISSUE THREAD

**Issue by dschulten** [asciidoctor/asciidoctor-reveal.js#168]
With `:icons: font` the callout is not shown with a number icon.

The rendered markup is
```html
<i class="conum" data-value="1"></i>
<b>(<span class="hljs-number">1</span>)</b>
```
It is shown as (**1**), not as a number "ball".
Reason: The original asciidoc.css contains the following style for conum[data-value], but that css is not included with a revealjs presentation. The original style hides the (1) and shows a number "ball" instead:

```css
<style>
.conum[data-value]{display:inline-block;color:#fff!important;background-color:rgba(50,150,50,.8);-webkit-border-radius:100px;border-radius:100px;text-align:center;font-size:.75em;width:1.67em;height:1.67em;line-height:1.67em;font-family:"Open Sans","DejaVu Sans",sans-serif;font-style:normal;font-weight:bold}
.conum[data-value] *{color:#fff!important}
.conum[data-value]+b{display:none}
.conum[data-value]:after{content:attr(data-value)}
pre .conum[data-value]{position:relative;top:-.125em}
b.conum *{color:inherit!important}
.conum:not([data-value]):empty{display:none}
</style>
```
Suggestion: asciidoctor-reveal.js should apply that style if icons:font is present.
