### ISSUE TITLE
Tables do not listen to "grid" and "frames" options

### ISSUE THREAD

**Issue by wackywendell** [asciidoctor/asciidoctor-reveal.js#29]
Try this with `asciidoctor` with and without this backend:

``` asciidoc
[grid="all",frame="all",options="header"]
|==========================
| Test | Test 2 | Test 3
| More | Again  | And again
|==========================
```

The grid and frame shows up for regular asciidoctor, but not with reveal.js. It seems that there are some classes missing: 

``` css
table.grid-all th.tableblock,table.grid-all td.tableblock{border-width:0 1px 1px 0}
table.grid-all tfoot>tr>th.tableblock,table.grid-all tfoot>tr>td.tableblock{border-width:1px 1px 0 0}
table.grid-cols th.tableblock,table.grid-cols td.tableblock{border-width:0 1px 0 0}
table.grid-all *>tr>.tableblock:last-child,table.grid-cols *>tr>.tableblock:last-child{border-right-width:0}
table.grid-rows th.tableblock,table.grid-rows td.tableblock{border-width:0 0 1px 0}
table.grid-all tbody>tr:last-child>th.tableblock,table.grid-all tbody>tr:last-child>td.tableblock,table.grid-all thead:last-child>tr>th.tableblock,table.grid-rows tbody>tr:last-child>th.tableblock,table.grid-rows tbody>tr:last-child>td.tableblock,table.grid-rows thead:last-child>tr>th.tableblock{border-bottom-width:0}
table.grid-rows tfoot>tr>th.tableblock,table.grid-rows tfoot>tr>td.tableblock{border-width:1px 0 0 0}
table.frame-all{border-width:1px}
table.frame-sides{border-width:0 1px}
table.frame-topbot{border-width:1px 0}
```

Those rules show up in the regular asciidoctor document, but not the asciidoctor-reveal.js one.
