### ISSUE TITLE
Use a neutral background color for callout

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-reveal.js#293]
Is there a particular reason to use a green background on callout?

https://github.com/asciidoctor/asciidoctor-reveal.js/blob/48b76bc6913281747e1e534d3d76aa9af37c37e8/templates/asciidoctor_revealjs.css.slim#L53

The default stylesheet is using a black background with a with font:

```css
.conum[data-value] {
  color: #fff!important;
  background: rgba(0,0,0,.8);
}
```
https://github.com/asciidoctor/asciidoctor/blob/master/data/stylesheets/asciidoctor-default.css

I think we should use a neutral color because depending on the chosen reveal.js theme, this green background might look out of place.
